# Generated by Django 4.1.7 on 2023-03-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0004_tripdetails_trip_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='secretspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spot_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=400)),
                ('spot_images', models.ImageField(upload_to='static\\images')),
                ('desc', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.profile')),
            ],
        ),
    ]
