# Generated by Django 4.1.7 on 2023-03-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0006_review_loaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_loaction',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
