# Generated by Django 4.1.7 on 2023-03-25 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0007_alter_review_loaction_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='static/images')),
                ('image2', models.ImageField(upload_to='static/images')),
                ('image3', models.ImageField(upload_to='static/images')),
                ('image4', models.ImageField(upload_to='static/images')),
                ('image5', models.ImageField(upload_to='static/images')),
                ('desc', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_interface.category')),
            ],
        ),
        migrations.DeleteModel(
            name='destinations',
        ),
    ]
